# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory to /client
WORKDIR /client

# Copy the current directory contents into the container at /client
COPY . /client

# Install any needed packages
RUN npm install

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Run the app
CMD ["npm", "start"]
