FROM python:3.10-slim-buster

# Set working directory
WORKDIR /app

# Install dependencies
COPY gradio/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Set environment variables
ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/app:${PATH}"

# Set command to run when container starts
CMD ["python", "gradio_app.py"]

